name: curl_testing
description: some tests for client-side Dart code to generate in curlconverter
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  http: ^0.13.5
  io: ^1.0.4
  path: ^1.6.4

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  test: ^1.24.1
