name: curl_testing
description: some tests for client-side Dart code to generate in curlconverter
version: 0.1.0
homepage: https://www.example.com

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http: ^0.13.5
  path: ^1.6.4
  collection: ^1.17.1
  io: ^1.0.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
